### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported when building from source

### ISSUE THREAD

**Issue by Iratu** [funmaker/Hybooru#11]
Thanks for the quick solving and responding to the previous issue. just a small error I run into now.
I have to do 'export NODE_OPTIONS=--openssl-legacy-provider' to be able to compile the source since I'm running into a error message without doing that.

```
vu2008@server1:/var/www/test/Hybooru$ npm run start

> hybooru@1.4.6 start
> rm -rf build && webpack --config webpack/server.dev.babel.js

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/var/www/test/Hybooru/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/var/www/test/Hybooru/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/var/www/test/Hybooru/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/var/www/test/Hybooru/node_modules/webpack/lib/NormalModule.js:838:17)
    at handleParseResult (/var/www/test/Hybooru/node_modules/webpack/lib/NormalModule.js:903:10)
    at /var/www/test/Hybooru/node_modules/webpack/lib/NormalModule.js:994:4
    at processResult (/var/www/test/Hybooru/node_modules/webpack/lib/NormalModule.js:717:11)
    at /var/www/test/Hybooru/node_modules/webpack/lib/NormalModule.js:777:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0

```

Same error when trying to run `npm run build:prod` as well.

I found the workaround here: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by funmaker** [comment]
I can't reproduce this.
However it seems that webpack fixed it in latter versions. Could you try updating webpack and see if it resolves the issue? If that's it, I'll just bump webpack version in next release.

**Comment by Iratu** [comment]
Seems updating webpack has fixed that error, though I am getting the following warnings:
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  client.js (379 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (400 KiB)
      style.css
      client.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

**Comment by funmaker** [comment]
These are just warnings.
I've update webpack version in the newest release. This should resolve this issue.
