### ISSUE TITLE
ProductionRelease.zip Throws Error When Running `npm start`

### ISSUE THREAD

**Issue by prof-m** [funmaker/Hybooru#13]
Downloaded the ProductionRelease.zip for release 1.4.8. Extracted it into it's own directory, navigated to that directory, and ran `npm start` per the README, but got the following error:
```
npm start

> hybooru@1.4.8 start
> node server.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'source-map-support/register'
Require stack:
- /Users/someuser/personalProjects/HybooruProductionBuild/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.3501 (/Users/someuser/personalProjects/HybooruProductionBuild/server.js:299:51572)
    at n (/Users/someuser/personalProjects/HybooruProductionBuild/server.js:299:55531)
    at Object.8676 (/Users/someuser/personalProjects/HybooruProductionBuild/server.js:1:62118)
    at n (/Users/someuser/personalProjects/HybooruProductionBuild/server.js:299:55531)
    at /Users/someuser/personalProjects/HybooruProductionBuild/server.js:299:55956
    at Object.<anonymous> (/Users/someuser/personalProjects/HybooruProductionBuild/server.js:299:55965) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/someuser/personalProjects/HybooruProductionBuild/server.js'
  ]
}

Node.js v17.9.0
```

Reproduced on: 

- MacOSX 10.15.7 (Catalina), node v17.9.0, npm v8.5.5
- Ubuntu 20.04.4 LTS, node v16.14.0, npm v8.3.1

**Comment by funmaker** [comment]
You need to install dependencies first. Use `npm install`.
I've added missing step to README.

**Comment by prof-m** [comment]
Makes sense, thanks!
