### ISSUE TITLE
No support for files over 2GB

### ISSUE THREAD

**Issue by aaronata** [funmaker/Hybooru#4]
Rebuilding the hybooru database on a hydrus database that contains files larger then the max integer value will cause hybooru to crash.

```
/home/hydrus/Hybooru/node_modules/pg-protocol/src/parser.ts:369
      name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
                                                                    ^
error: value "2362677200" is out of range for type integer
    at Parser.parseErrorMessage (/home/hydrus/Hybooru/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/hydrus/Hybooru/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/hydrus/Hybooru/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.stream.on (/home/hydrus/Hybooru/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)```

**Comment by funmaker** [comment]
@aaronata Hi, thanks for the bug report.

This should be fixed in the newest release: [v1.4.2](https://github.com/funmaker/Hybooru/releases/tag/v1.4.2)
