### ISSUE TITLE
SqliteError: no such table: tag_parents

### ISSUE THREAD

**Issue by sbstratos79** [funmaker/Hybooru#45]
I am using the latest docker image i.e. 1.11.0
Hydrus version is 586.

Rebuilding database throws this error:
```
Rebuilding Database!

Posts                           [####################] Done in 1.20s
Urls                            [####################] Done in 1.75s
Notes                           [####################] Done in 15ms
Tags                            [####################] Done in 459ms
Mappings                        [####################] Done in 1.75s
Mappings                        [####################] Done in 4.61s
Mappings                        [####################] Done in 18ms
SqliteError: no such table: tag_parents
    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at i.total (/build/server/helpers/dbImport/import.ts:24:64)
    at i.<anonymous> (/build/server/helpers/dbImport/import.ts:49:24)
    at Generator.next (<anonymous>)
    at /app/server.js:229:1303
    at new Promise (<anonymous>)
    at a (/app/server.js:229:1048)
    at i.start (/app/server.js:229:1993)
    at Object.<anonymous> (/build/server/helpers/dbImport/index.ts:73:83)
    at Generator.next (<anonymous>) {
  code: 'SQLITE_ERROR'
}
```

**Comment by funmaker** [comment]
Fixed in v1.12.0
