### ISSUE TITLE
Unable to initialize DB

### ISSUE THREAD

**Issue by Wyrrrd** [funmaker/Hybooru#6]
Since the latest commit ([5e80669](https://github.com/funmaker/Hybooru/commit/5e806693416aa3f882dc78b2004ef525fe260a32)), Hybooru docker container throws the following error on fresh start (DB not initialized):

```
Rebuilding Database!

Unable to initialize DB!
SqliteError: no such table: current_files_4
    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at r.total (/build/server/helpers/dbImport/import.ts:20:24)
    at r.<anonymous> (/build/server/helpers/dbImport/import.ts:40:30)
    at Generator.next (<anonymous>)
    at /app/server.js:178:1303
    at new Promise (<anonymous>)
    at a (/app/server.js:178:1048)
    at r.start (/app/server.js:178:1859)
    at Object.<anonymous> (/build/server/helpers/dbImport/index.ts:61:69)
    at Generator.next (<anonymous>)
```

**Comment by funmaker** [comment]
@Wyrrrd Thanks for the issue.
Which Hydrus version do you use? You need Hydrus v447 at minimum for the latest release, as specified in readme.

**Comment by Wyrrrd** [comment]
Sorry to bother you, my automatism seems to be not automatic anymore. Version was 437, now everything works again...
